jobs:
- job: Linux
  dependsOn: GetReleaseVersion
  timeoutInMinutes: 180

  variables:
    ReleaseVersion: $[ dependencies.GetReleaseVersion.outputs['Version.ReleaseVersion'] ]
  pool:
    vmImage: ubuntu-16.04

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 8.9.3
    displayName: Install Node.js 8.9.3

  - script: npm install --global npm@6.2.0
    displayName: Update npm

  - script: |
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends build-essential xvfb clang-3.5 fakeroot git libsecret-1-dev rpm libx11-dev libxkbfile-dev xz-utils xorriso zsync libxss1 libgconf2-4 libgtk-3-0
    displayName: Install apt dependencies

  - script: script/bootstrap
    displayName: Bootstrap build environment
    env:
      CI: true
      CI_PROVIDER: VSTS

  - script: script/lint
    displayName: Run linter

  - script: |
      CC=clang-3.5 CXX=clang++-3.5 npm_config_clang=1 script/build --no-bootstrap --create-debian-package --create-rpm-package --compress-artifacts
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
      ATOM_RELEASE_VERSION: $(ReleaseVersion)
    displayName: Build Atom

  - script: |
      sudo /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16
      export DISPLAY=':99.0'
      Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      script/test
    env:
      CI: true
      CI_PROVIDER: VSTS
      ATOM_JASMINE_REPORTER: list
      TEST_JUNIT_XML_ROOT: $(Common.TestResultsDirectory)/junit
    displayName: Run tests
    condition: and(succeeded(), ne(variables['Atom.SkipTests'], 'true'))

  - script: script/postprocess-junit-results --search-folder "${TEST_JUNIT_XML_ROOT}" --test-results-files "**/*.xml"
    env:
      TEST_JUNIT_XML_ROOT: $(Common.TestResultsDirectory)/junit
    displayName: Post-process test results
    condition: ne(variables['Atom.SkipTests'], 'true')

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: JUnit
      searchFolder: $(Common.TestResultsDirectory)/junit
      testResultsFiles: "**/*.xml"
      mergeTestResults: true
      testRunTitle: Linux
    condition: ne(variables['Atom.SkipTests'], 'true')

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.SourcesDirectory)/out/atom.x86_64.rpm
      ArtifactName: atom.x86_64.rpm
      ArtifactType: Container
    displayName: Upload atom.x84_64.rpm
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.SourcesDirectory)/out/atom-amd64.deb
      ArtifactName: atom-amd64.deb
      ArtifactType: Container
    displayName: Upload atom-amd64.deb
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.SourcesDirectory)/out/atom-amd64.tar.gz
      ArtifactName: atom-amd64.tar.gz
      ArtifactType: Container
    displayName: Upload atom-amd64.tar.gz
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
