resources:
  containers:
  - container: atom-linux-ci
    image: daviwil/atom-linux-ci:latest

jobs:

- job: GetReleaseVersion
  steps:
  # This has to be done separately because VSTS inexplicably
  # exits the script block after `npm install` completes.
  - script: |
      cd script\vsts
      npm install
    displayName: npm install
  - script: node script\vsts\get-release-version.js
    name: Version

# Import OS-specific build definitions
- template: platforms/windows.yml
- template: platforms/macos.yml
- template: platforms/linux.yml

- job: Release
  pool:
    vmImage: vs2015-win2012r2 # needed for Python 2.7 and gyp

  dependsOn:
  - GetReleaseVersion
  - Windows
  - Linux
  - macOS

  variables:
    ReleaseVersion: $[ dependencies.GetReleaseVersion.outputs['Version.ReleaseVersion'] ]

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 8.9.3
    displayName: Install Node.js 8.9.3

  # This has to be done separately because VSTS inexplicably
  # exits the script block after `npm install` completes.
  - script: |
      cd script
      npm install
    displayName: npm install

  - task: DownloadBuildArtifacts@0
    inputs:
      itemPattern: '**'
      downloadType: 'specific'
    displayName: Download Release Artifacts

  - script: |
      echo "Do your artifact uploads here!"
      # $(Build.SourcesDirectory)\script\publish-release.cmd --create-github-release --assets-path "$(System.ArtifactsDirectory)"
    env:
      ATOM_RELEASE_VERSION: $(ReleaseVersion)
    displayName: Upload Release Artifacts
